name: Deploy to OceanIt Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd dashboard.ocean-it.net/Ocean
            git pull origin main
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache

